package pojo;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// default package
// Generated Aug 14, 2019 12:44:01 AM by Hibernate Tools 5.4.3.Final

/**
 * SinhVien generated by hbm2java
 */
@Entity
@Table(name = "sinhvien")
public class SinhVien implements java.io.Serializable {
	@Id
	private String masv;
	private String hoten;
	private String gioitinh;
	private String cmnd;

	public SinhVien() {
	}


	public SinhVien(String masv, String hoten, String gioitinh, String cmnd) {
		this.masv = masv;
		this.hoten = hoten;
		this.gioitinh = gioitinh;
		this.cmnd = cmnd;
	}

	public String getMasv() {
		return this.masv;
	}

	public void setMasv(String masv) {
		this.masv = masv;
	}

	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	public String getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(String gioitinh) {
		this.gioitinh = gioitinh;
	}

	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

}
