package pojo;
// default package
// Generated Aug 14, 2019 12:44:01 AM by Hibernate Tools 5.4.3.Final

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SvPhucKhao generated by hbm2java
 */
@Entity
@Table(name = "sv_phuckhao")
public class SvPhucKhao implements java.io.Serializable {
	@Id
	private int id;
	private String masv;
	private String malop;
	private String trangthai;
	public SvPhucKhao() {
	}

	public SvPhucKhao(String masv, String malop, String trangthai) {
		this.masv = masv;
		this.malop = malop;
		this.trangthai = trangthai;
	}

	public String getMasv() {
		return this.masv;
	}

	public void setMasv(String masv) {
		this.masv = masv;
	}

	public String getMalop() {
		return this.malop;
	}

	public void setMalop(String malop) {
		this.malop = malop;
	}

	public String getTrangthai() {
		return trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}
	
}
