package pojo;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserPass generated by hbm2java
 */
@Entity
@Table(name = "user_pass")
public class UserPass implements java.io.Serializable {
	@Id
	private String username;
	private String password;

	public UserPass() {
	}

	public UserPass(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
